version: '3.4'

services:
#   transmission:
#     volumes:
#       - 'D:\Temp\media:/downloads'
#       - 'D:\Temp\media\torrents:/torrents'
  minidlna:
    volumes:
      - 'D:\Temp\media:/media'
      - '.\minidlna:/minidlna'
#  gerbera:
#    volumes:
#      - 'D:\Temp\media:/media'