FROM ubuntu:16.04 as BUILD

RUN apt-get update && apt-get install -y automake autoconf libtool pkg-config intltool libcurl4-openssl-dev libglib2.0-dev libevent-dev libminiupnpc-dev libgtk-3-dev libappindicator3-dev libssl-dev cmake
